#!/bin/bash

## This install script can be used as you like. Use it to add repositories,
## install software using apt-get or compile source code.
## Always make sure you test your script on a fresh install of remasterpi,
## this way you are less likely to forget dependencies required
## by your script.

## Check and Install required dependencies
# depcheck(){
	# for deps in dep1 dep2 dep3 dep4 dep5 ; do
	# 	if [ -f $deps ] ; then
	#		echo "$deps ==> Installed"
	# 	else
	#		echo "Adding $deps to Install list"
	#		DEPLIST="$DEPLIST $deps"
	# 	fi
	# done
  ## Install dependencies stored in the DepList
	#echo && echo 'Installing dependencies required by the install script'
	#echo
	# aptinstall -y "$DEPLIST"
# }


## Use apt-get or faster-apt (type 'apthelp' for faster-apt command list) to
## installsoftware packages from the configured repositories.
#
# echo 'Updating the repositories:'
# echo
# apt-update
# echo
# echo 'Installing some software packages'
# apt-minimal install -y git-core rsync
# aptinstall -y wicd-curses 
# echo
# echo 'All packages have been installed'

## Install deb packages not available from a repository
#
# wget http://some-server/something/debs/your-package.deb
# apt-localinstall your-package.deb

## Install some binary tar archive
#
# wget http://some-server/somehing/your-project.tar.gz
# tar xvzf your-project.tar.gz -C /usr/local/
# chmod +x /usr/local/your-project/bin/executable
# ln -s /usr/local/your-project/bin/executable /usr/bin/your-project

## Install some source package from a git repository
#
cd /usr/src
 git clone https://github.com/socialdefect/rasp-get.git
ln -s rasp-get/rasp-get.sh /usr/bin/rasp-get
ln -s rasp-get/arch.functions /usr/local/bin/
ln -s rasp-get/debian.functions /usr/local/bin/
ln -s rasp-get/rhel.functions /usr/local/bin/
ln -s rasp-get/rasp-get.conf /etc/

# cd your-project
# ./configure && make && make install
# if [ "$?" != '0' ] ; then
#	echo 'Failed to build the source package!!!'
#	exit 1
# else
#	echo 'Source package has been succesfuly compiled and installed.'
# fi

## Use basic unix tools to configure the system
# echo 'Configuring your system...'
# echo
# echo 'PATH="/usr/local/bin:/sbin:/usr/sbin:$PATH"' >> /etc/bash.bashrc
# mkdir -v /usr/local/new-dir
# chmod u+x /usr/local/bin/your-script

echo && echo 'Make sure to edit the file /etc/rasp-get.conf and set your OS!!'

exit 0
